import { BusRouteOption, ParcelRecord, PaymentMethodOption } from './types';

export const TANZANIAN_CITIES = [
  "Dar es Salaam",
  "Arusha",
  "Mwanza",
  "Dodoma",
  "Mbeya",
  "Morogoro",
  "Tanga",
  "Zanzibar",
  "Moshi",
  "Iringa",
];

export const BUS_OPERATORS: BusRouteOption[] = [
  {
    id: "bus-1",
    operator: "BM Coach",
    operatorLogoBg: "bg-blue-600",
    from: "Dar es Salaam",
    to: "Arusha",
    departureTime: "08:00",
    arrivalTime: "14:30",
    price: 15000,
  },
  {
    id: "bus-2",
    operator: "Shabiby Line",
    operatorLogoBg: "bg-emerald-600",
    from: "Dar es Salaam",
    to: "Dodoma",
    departureTime: "07:30",
    arrivalTime: "13:00",
    price: 12000,
  },
  {
    id: "bus-3",
    operator: "Abood Bus Service",
    operatorLogoBg: "bg-amber-600",
    from: "Dar es Salaam",
    to: "Morogoro",
    departureTime: "09:15",
    arrivalTime: "12:15",
    price: 10000,
  },
  {
    id: "bus-4",
    operator: "Kimbinyiko Express",
    operatorLogoBg: "bg-red-600",
    from: "Arusha",
    to: "Mwanza",
    departureTime: "06:00",
    arrivalTime: "15:00",
    price: 22000,
  },
  {
    id: "bus-5",
    operator: "Machame Express",
    operatorLogoBg: "bg-purple-600",
    from: "Dar es Salaam",
    to: "Moshi",
    departureTime: "07:00",
    arrivalTime: "14:00",
    price: 18000,
  },
];

export const PAYMENT_METHODS: PaymentMethodOption[] = [
  {
    id: "mpesa",
    name: "M-Pesa",
    description: "Vodacom Mobile Money",
    color: "bg-red-600",
    logoText: "M",
  },
  {
    id: "tigopesa",
    name: "Tigo Pesa",
    description: "Tigo Mobile Money",
    color: "bg-blue-600",
    logoText: "T",
  },
  {
    id: "airtel",
    name: "Airtel Money",
    description: "Airtel Mobile Money",
    color: "bg-red-700",
    logoText: "A",
  },
  {
    id: "halopesa",
    name: "Halopesa",
    description: "Halotel Mobile Money",
    color: "bg-orange-500",
    logoText: "H",
  },
];

export const INITIAL_PARCELS: ParcelRecord[] = [
  {
    id: "p-1",
    code: "BP-7890",
    from: "Dar es Salaam",
    to: "Arusha",
    busOperator: "BM Coach",
    departureTime: "08:00",
    arrivalTime: "14:30",
    price: 15000,
    date: "Today",
    status: "On the way",
    parcelType: "Medium package",
    weight: "3.5 kg",
    senderName: "Juma Hassan",
    senderPhone: "+255 712 345 678",
    receiverName: "Amina Rashid",
    receiverPhone: "+255 754 987 654",
    receiverLocation: "Arusha Central Bus Terminal",
    paymentMethod: "M-Pesa",
    createdAt: "2025-05-10 07:15",
    timeline: [
      { title: "Payment confirmed", timestamp: "07:15 AM", completed: true, current: false },
      { title: "Parcel received at station", timestamp: "07:40 AM", completed: true, current: false },
      { title: "Bus departed", timestamp: "08:05 AM", completed: true, current: false },
      { title: "On the way", description: "Passing Morogoro region", timestamp: "11:20 AM", completed: true, current: true },
      { title: "Arrived in Arusha", timestamp: "Expected 14:30", completed: false, current: false },
      { title: "Collected by receiver", completed: false, current: false },
    ],
  },
  {
    id: "p-2",
    code: "BP-5621",
    from: "Arusha",
    to: "Mwanza",
    busOperator: "Kimbinyiko Express",
    departureTime: "06:00",
    arrivalTime: "15:00",
    price: 22000,
    date: "Yesterday",
    status: "Collected",
    parcelType: "Document",
    weight: "0.5 kg",
    senderName: "Juma Hassan",
    senderPhone: "+255 712 345 678",
    receiverName: "Godfrey Kilonzo",
    receiverPhone: "+255 768 112 233",
    receiverLocation: "Nyegezi Bus Terminal, Mwanza",
    paymentMethod: "Tigo Pesa",
    createdAt: "2025-05-09 05:45",
    timeline: [
      { title: "Payment confirmed", timestamp: "Yesterday 05:45 AM", completed: true, current: false },
      { title: "Parcel received at station", timestamp: "Yesterday 05:55 AM", completed: true, current: false },
      { title: "Bus departed", timestamp: "Yesterday 06:10 AM", completed: true, current: false },
      { title: "On the way", timestamp: "Yesterday 11:00 AM", completed: true, current: false },
      { title: "Arrived in Mwanza", timestamp: "Yesterday 15:10 PM", completed: true, current: false },
      { title: "Collected by receiver", timestamp: "Yesterday 16:00 PM", completed: true, current: true },
    ],
  },
];
